### ISSUE TITLE
What this component do?

### ISSUE THREAD

**Issue by divined** [patrik-piskay/react-tabs-redux#27]
Why y not include changeSelectedTab inside your component?

**Comment by divined** [comment]
If i cange <Tabs /> to <div />
<TabLink /> to <div onClick=store.dispatch('changeActiveTab')/>
<TabContent /> to {this.props.tabs.activeTab && <div>content</div>

I will get your component. My question is: what your component do? If i must to write all this funcions?
It only check this.props.tabs.activeTab and show activeTab ?????

**Comment by patrik-piskay** [comment]
The purpose of this library is to make working with tabs declarative and reusable by providing these compound components that can be used without any UI restrictions, instead of writing imperative code, by taking advantage of React's component model. 

Sure, in Redux scenario there is more code that needs to be provided to this `Tabs` component, but if storing the information about the currently selected tab into a global store is not necessarily needed and we are fine for Tabs to have it's own local state, it just works without any additional code.

Also, you can always implement your own solution if you don't feel like using a lib if it makes sense in your use case.
