### ISSUE TITLE
Unknown props warning

### ISSUE THREAD

**Issue by char0n** [patrik-piskay/react-tabs-redux#4]
Hi,

I am always getting this warning in console  when using the library. I guess it have something to do with react props validation.

Warning:
`warning.js:44 Warning: Unknown props `selectedTab`, `handleSelect` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop`

React: =15.2.1
react-redux: =4.4.5
redux: =3.5.2
react-tabs-redux: =1.3.0

**Comment by patrik-piskay** [comment]
Hi @char0n, thanks for reporting! I'll fix it when I get a chance later today/tomorrow, but feel free to send a PR yourself. 

The issue is with [this line](https://github.com/patrik-piskay/react-tabs-redux/blob/master/src/components/Tabs.js#L97) where we are passing every prop to the `div` element while the latest React expects only valid DOM properties to be passed to DOM elements. 

The approach of passing all the props that were passed to `<Tabs />` component that are not expected by the component (`className`, `style`, `onClick`, etc.) down to the `div` element should do it (see [React docs](https://facebook.github.io/react/warnings/unknown-prop.html) for reference).

**Comment by char0n** [comment]
Hi @patrik-piskay, I'll try to provide pull request myself. Thanks

**Comment by char0n** [comment]
Pull request created. @patrik-piskay  waiting for review ;]

All tests passed.

**Comment by char0n** [comment]
@patrik-piskay Thanks for pointing other props out. I enumerated additional props and rebased the pull request.

**Comment by brahma-dev** [comment]
I'm facing a similar issue where it conflicts with [Link](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/Link.md) from React-Router because it has a prop named `to`.

See: https://github.com/patrik-piskay/react-tabs-redux/blob/9f341fb7e702151c3cadd01ec00788f340116d0d/src/components/Tabs.js#L62
